# Generated by Django 5.2.6 on 2025-10-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docubase_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='docubase_app.etiqueta'),
        ),
    ]
