# Generated by Django 5.2.6 on 2025-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docubase_app', '0003_proyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='docubase_app.etiqueta'),
        ),
    ]
